name: Assign issue

on: [issue_comment]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - uses: datapythonista/github-action-assign@v0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        keyword: 'working on this'
